### ISSUE TITLE
Don't use terminal colors if not supported

### ISSUE THREAD

**Issue by netromdk** [weareburator/blurator#23]
Don't use terminal colors, e.g. "\033[0;37m", when not supported. In the windows prompt it isn't as the attachment beneath shows. Find a way to detect if supported and otherwise don't use it.

![image 2015-03-07 at 9 09 19 pm](https://cloud.githubusercontent.com/assets/5989057/6543197/d6c35ee4-c512-11e4-908c-19c234e8ddcb.png)

**Comment by netromdk** [comment]
Or just disable on Windows explicitly.

**Comment by voidPirate** [comment]
Disable only on Windows. Just my .2
