### ISSUE TITLE
Implement parser class and CLI syntax

### ISSUE THREAD

**Issue by voidPirate** [weareburator/blurator#7]
As I work on the parser, I'd also like to construct the finally syntax for the CLI. 
See below for the syntax I envision for it.
`./blurator [images_path] --faces --plates [watermark_path] --upper-left`

`--faces`, `--plates`, path to watermark and placement are all optional. If no additional arguments are passed other than the path to images to process, then we can display a simple message with help information like: `Nothing to do for these images see 'blurator --help'`

**Comment by voidPirate** [comment]
The following has been implemented now, with appropriate action for each including error handling.
```
% ./bin/blurator -h
Usage: ./bin/blurator [options] path
Blur license plates and faces

Options:
  -h, --help     Displays this help.
  -v, --version  Displays version information.
  -f, --faces    Detect faces
  -p, --plates   Detect license plates
  --no-backup    Don't store a backup of the original image

Arguments:
  path           Path to images or image
```

Since this is a simple command line parser, I decided to just keep it contained inside ```main.cpp```.
> Btw. we can make it default to save a ".bak" backup file. Then instead of using ```--backup``` we will have a ```--no-backup``` if they explicitly don't want the backup files. What do you think about that?

I do like the option for making it not save a backup, I can see users forgetting to set the option if we do it the other way, thus pissing them off because it overwrote the original image.

**Comment by netromdk** [comment]
We both agree. Let's close this issue. :)
